baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Vald"
theme = "vald"
publishDir = "tmp_pre"
disableKinds = "RSS"
[markup.goldmark.renderer]
    unsafe= true
[params]
    description = "Vald is high scalable distributed high-speed approximate nearest neighbor search engine"
