baseURL = "https://vald.vdaas.org"
languageCode = "en-us"
title = "Vald"
theme = "vald"
publishDir = "tmp_pre"
disableKinds = "RSS"
googleAnalytics = "UA-164223416-1"
enableEmoji=true
[markup.goldmark.renderer]
    unsafe= true
