name: Lint description
on: [pull_request]
jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Git config
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Setup node/npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install textlint
        run: |
          npm init -y
          npm install --save-dev textlint textlint-rule-en-spell textlint-rule-prh textlint-rule-write-good
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          textlint_flags: "./description.json"
